# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  numbersapp:
    image: numbersapp
    build:
      context: .
      dockerfile: NumbersApp/Dockerfile
    ports:
      - 8000:8000
